-- V5: 事务传播行为演示表
CREATE TABLE IF NOT EXISTS tx_demo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL COMMENT '用于验证提交/回滚的记录名',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事务传播行为演示';
